name: myproject

services:
  web:
    #build:
      #context: ..
      #dockerfile: Dockerfile
    image: supreecha2003/postgresweb:<IMAGE_TAG>
    container_name: web
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432

    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      retries: 20
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
